/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.me.expense.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ExpenseItem service. Represents a row in the &quot;ExpenseManager_ExpenseItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.me.expense.manager.model.impl.ExpenseItemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.me.expense.manager.model.impl.ExpenseItemImpl</code>.
 * </p>
 *
 * @author Mahmoud Hussein Tayem
 * @see ExpenseItem
 * @generated
 */
@ProviderType
public interface ExpenseItemModel
	extends BaseModel<ExpenseItem>, GroupedModel, ShardedModel,
			WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expense item model instance should use the {@link ExpenseItem} interface instead.
	 */

	/**
	 * Returns the primary key of this expense item.
	 *
	 * @return the primary key of this expense item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this expense item.
	 *
	 * @param primaryKey the primary key of this expense item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the expense item ID of this expense item.
	 *
	 * @return the expense item ID of this expense item
	 */
	public long getExpenseItemId();

	/**
	 * Sets the expense item ID of this expense item.
	 *
	 * @param expenseItemId the expense item ID of this expense item
	 */
	public void setExpenseItemId(long expenseItemId);

	/**
	 * Returns the group ID of this expense item.
	 *
	 * @return the group ID of this expense item
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this expense item.
	 *
	 * @param groupId the group ID of this expense item
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this expense item.
	 *
	 * @return the company ID of this expense item
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this expense item.
	 *
	 * @param companyId the company ID of this expense item
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this expense item.
	 *
	 * @return the user ID of this expense item
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this expense item.
	 *
	 * @param userId the user ID of this expense item
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this expense item.
	 *
	 * @return the user uuid of this expense item
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this expense item.
	 *
	 * @param userUuid the user uuid of this expense item
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this expense item.
	 *
	 * @return the user name of this expense item
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this expense item.
	 *
	 * @param userName the user name of this expense item
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this expense item.
	 *
	 * @return the create date of this expense item
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this expense item.
	 *
	 * @param createDate the create date of this expense item
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this expense item.
	 *
	 * @return the modified date of this expense item
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this expense item.
	 *
	 * @param modifiedDate the modified date of this expense item
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the date incurred of this expense item.
	 *
	 * @return the date incurred of this expense item
	 */
	public Date getDateIncurred();

	/**
	 * Sets the date incurred of this expense item.
	 *
	 * @param dateIncurred the date incurred of this expense item
	 */
	public void setDateIncurred(Date dateIncurred);

	/**
	 * Returns the title of this expense item.
	 *
	 * @return the title of this expense item
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this expense item.
	 *
	 * @param title the title of this expense item
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this expense item.
	 *
	 * @return the description of this expense item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this expense item.
	 *
	 * @param description the description of this expense item
	 */
	public void setDescription(String description);

	/**
	 * Returns the type of this expense item.
	 *
	 * @return the type of this expense item
	 */
	public long getType();

	/**
	 * Sets the type of this expense item.
	 *
	 * @param type the type of this expense item
	 */
	public void setType(long type);

	/**
	 * Returns the reimburse of this expense item.
	 *
	 * @return the reimburse of this expense item
	 */
	public boolean getReimburse();

	/**
	 * Returns <code>true</code> if this expense item is reimburse.
	 *
	 * @return <code>true</code> if this expense item is reimburse; <code>false</code> otherwise
	 */
	public boolean isReimburse();

	/**
	 * Sets whether this expense item is reimburse.
	 *
	 * @param reimburse the reimburse of this expense item
	 */
	public void setReimburse(boolean reimburse);

	/**
	 * Returns the amount of this expense item.
	 *
	 * @return the amount of this expense item
	 */
	public Long getAmount();

	/**
	 * Sets the amount of this expense item.
	 *
	 * @param amount the amount of this expense item
	 */
	public void setAmount(Long amount);

	/**
	 * Returns the expense ID of this expense item.
	 *
	 * @return the expense ID of this expense item
	 */
	public long getExpenseId();

	/**
	 * Sets the expense ID of this expense item.
	 *
	 * @param expenseId the expense ID of this expense item
	 */
	public void setExpenseId(long expenseId);

	/**
	 * Returns the status by user ID of this expense item.
	 *
	 * @return the status by user ID of this expense item
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this expense item.
	 *
	 * @param statusByUserId the status by user ID of this expense item
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this expense item.
	 *
	 * @return the status by user uuid of this expense item
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this expense item.
	 *
	 * @param statusByUserUuid the status by user uuid of this expense item
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this expense item.
	 *
	 * @return the status by user name of this expense item
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this expense item.
	 *
	 * @param statusByUserName the status by user name of this expense item
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this expense item.
	 *
	 * @return the status date of this expense item
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this expense item.
	 *
	 * @param statusDate the status date of this expense item
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the status of this expense item.
	 *
	 * @return the status of this expense item
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this expense item.
	 *
	 * @param status the status of this expense item
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns <code>true</code> if this expense item is approved.
	 *
	 * @return <code>true</code> if this expense item is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this expense item is denied.
	 *
	 * @return <code>true</code> if this expense item is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this expense item is a draft.
	 *
	 * @return <code>true</code> if this expense item is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this expense item is expired.
	 *
	 * @return <code>true</code> if this expense item is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this expense item is inactive.
	 *
	 * @return <code>true</code> if this expense item is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this expense item is incomplete.
	 *
	 * @return <code>true</code> if this expense item is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this expense item is pending.
	 *
	 * @return <code>true</code> if this expense item is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this expense item is scheduled.
	 *
	 * @return <code>true</code> if this expense item is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}