/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.me.expense.manager.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Translation service. Represents a row in the &quot;ExpenseManager_Translation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.me.expense.manager.model.impl.TranslationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.me.expense.manager.model.impl.TranslationImpl</code>.
 * </p>
 *
 * @author Mahmoud Hussein Tayem
 * @see Translation
 * @generated
 */
@ProviderType
public interface TranslationModel
	extends BaseModel<Translation>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a translation model instance should use the {@link Translation} interface instead.
	 */

	/**
	 * Returns the primary key of this translation.
	 *
	 * @return the primary key of this translation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this translation.
	 *
	 * @param primaryKey the primary key of this translation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the translation ID of this translation.
	 *
	 * @return the translation ID of this translation
	 */
	public long getTranslationId();

	/**
	 * Sets the translation ID of this translation.
	 *
	 * @param translationId the translation ID of this translation
	 */
	public void setTranslationId(long translationId);

	/**
	 * Returns the group ID of this translation.
	 *
	 * @return the group ID of this translation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this translation.
	 *
	 * @param groupId the group ID of this translation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this translation.
	 *
	 * @return the company ID of this translation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this translation.
	 *
	 * @param companyId the company ID of this translation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this translation.
	 *
	 * @return the user ID of this translation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this translation.
	 *
	 * @param userId the user ID of this translation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this translation.
	 *
	 * @return the user uuid of this translation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this translation.
	 *
	 * @param userUuid the user uuid of this translation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this translation.
	 *
	 * @return the user name of this translation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this translation.
	 *
	 * @param userName the user name of this translation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this translation.
	 *
	 * @return the create date of this translation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this translation.
	 *
	 * @param createDate the create date of this translation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this translation.
	 *
	 * @return the modified date of this translation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this translation.
	 *
	 * @param modifiedDate the modified date of this translation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the portlet ID of this translation.
	 *
	 * @return the portlet ID of this translation
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this translation.
	 *
	 * @param portletId the portlet ID of this translation
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the component ID of this translation.
	 *
	 * @return the component ID of this translation
	 */
	@AutoEscape
	public String getComponentId();

	/**
	 * Sets the component ID of this translation.
	 *
	 * @param componentId the component ID of this translation
	 */
	public void setComponentId(String componentId);

	/**
	 * Returns the key of this translation.
	 *
	 * @return the key of this translation
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this translation.
	 *
	 * @param key the key of this translation
	 */
	public void setKey(String key);

	/**
	 * Returns the culture code of this translation.
	 *
	 * @return the culture code of this translation
	 */
	@AutoEscape
	public String getCultureCode();

	/**
	 * Sets the culture code of this translation.
	 *
	 * @param cultureCode the culture code of this translation
	 */
	public void setCultureCode(String cultureCode);

	/**
	 * Returns the translation value of this translation.
	 *
	 * @return the translation value of this translation
	 */
	@AutoEscape
	public String getTranslationValue();

	/**
	 * Sets the translation value of this translation.
	 *
	 * @param translationValue the translation value of this translation
	 */
	public void setTranslationValue(String translationValue);

}