/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.me.expense.manager.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.me.expense.manager.model.ExpenseItemType;
import com.liferay.me.expense.manager.model.ExpenseItemTypeModel;
import com.liferay.me.expense.manager.model.ExpenseItemTypeSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ExpenseItemType service. Represents a row in the &quot;ExpenseManager_ExpenseItemType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ExpenseItemTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExpenseItemTypeImpl}.
 * </p>
 *
 * @author Mahmoud Hussein Tayem
 * @see ExpenseItemTypeImpl
 * @generated
 */
@JSON(strict = true)
public class ExpenseItemTypeModelImpl
	extends BaseModelImpl<ExpenseItemType> implements ExpenseItemTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a expense item type model instance should use the <code>ExpenseItemType</code> interface instead.
	 */
	public static final String TABLE_NAME = "ExpenseManager_ExpenseItemType";

	public static final Object[][] TABLE_COLUMNS = {
		{"expenseItemTypeId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"value", Types.VARCHAR}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("expenseItemTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ExpenseManager_ExpenseItemType (expenseItemTypeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,value VARCHAR(75) null,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table ExpenseManager_ExpenseItemType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY expenseItemType.expenseItemTypeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ExpenseManager_ExpenseItemType.expenseItemTypeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPENSEITEMTYPEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ExpenseItemType toModel(ExpenseItemTypeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ExpenseItemType model = new ExpenseItemTypeImpl();

		model.setExpenseItemTypeId(soapModel.getExpenseItemTypeId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTitle(soapModel.getTitle());
		model.setValue(soapModel.getValue());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ExpenseItemType> toModels(
		ExpenseItemTypeSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<ExpenseItemType> models = new ArrayList<ExpenseItemType>(
			soapModels.length);

		for (ExpenseItemTypeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ExpenseItemTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _expenseItemTypeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setExpenseItemTypeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _expenseItemTypeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExpenseItemType.class;
	}

	@Override
	public String getModelClassName() {
		return ExpenseItemType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ExpenseItemType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ExpenseItemType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExpenseItemType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ExpenseItemType)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ExpenseItemType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ExpenseItemType, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ExpenseItemType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ExpenseItemType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ExpenseItemType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ExpenseItemType>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ExpenseItemType.class.getClassLoader(), ExpenseItemType.class,
			ModelWrapper.class);

		try {
			Constructor<ExpenseItemType> constructor =
				(Constructor<ExpenseItemType>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ExpenseItemType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ExpenseItemType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ExpenseItemType, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ExpenseItemType, Object>>();
		Map<String, BiConsumer<ExpenseItemType, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ExpenseItemType, ?>>();

		attributeGetterFunctions.put(
			"expenseItemTypeId", ExpenseItemType::getExpenseItemTypeId);
		attributeSetterBiConsumers.put(
			"expenseItemTypeId",
			(BiConsumer<ExpenseItemType, Long>)
				ExpenseItemType::setExpenseItemTypeId);
		attributeGetterFunctions.put("groupId", ExpenseItemType::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ExpenseItemType, Long>)ExpenseItemType::setGroupId);
		attributeGetterFunctions.put(
			"companyId", ExpenseItemType::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ExpenseItemType, Long>)ExpenseItemType::setCompanyId);
		attributeGetterFunctions.put("userId", ExpenseItemType::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<ExpenseItemType, Long>)ExpenseItemType::setUserId);
		attributeGetterFunctions.put("userName", ExpenseItemType::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ExpenseItemType, String>)ExpenseItemType::setUserName);
		attributeGetterFunctions.put(
			"createDate", ExpenseItemType::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ExpenseItemType, Date>)ExpenseItemType::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ExpenseItemType::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ExpenseItemType, Date>)
				ExpenseItemType::setModifiedDate);
		attributeGetterFunctions.put("title", ExpenseItemType::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<ExpenseItemType, String>)ExpenseItemType::setTitle);
		attributeGetterFunctions.put("value", ExpenseItemType::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<ExpenseItemType, String>)ExpenseItemType::setValue);
		attributeGetterFunctions.put("status", ExpenseItemType::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<ExpenseItemType, Integer>)ExpenseItemType::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getExpenseItemTypeId() {
		return _expenseItemTypeId;
	}

	@Override
	public void setExpenseItemTypeId(long expenseItemTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expenseItemTypeId = expenseItemTypeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalExpenseItemTypeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("expenseItemTypeId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ExpenseItemType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExpenseItemType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ExpenseItemType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExpenseItemTypeImpl expenseItemTypeImpl = new ExpenseItemTypeImpl();

		expenseItemTypeImpl.setExpenseItemTypeId(getExpenseItemTypeId());
		expenseItemTypeImpl.setGroupId(getGroupId());
		expenseItemTypeImpl.setCompanyId(getCompanyId());
		expenseItemTypeImpl.setUserId(getUserId());
		expenseItemTypeImpl.setUserName(getUserName());
		expenseItemTypeImpl.setCreateDate(getCreateDate());
		expenseItemTypeImpl.setModifiedDate(getModifiedDate());
		expenseItemTypeImpl.setTitle(getTitle());
		expenseItemTypeImpl.setValue(getValue());
		expenseItemTypeImpl.setStatus(getStatus());

		expenseItemTypeImpl.resetOriginalValues();

		return expenseItemTypeImpl;
	}

	@Override
	public int compareTo(ExpenseItemType expenseItemType) {
		long primaryKey = expenseItemType.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ExpenseItemType)) {
			return false;
		}

		ExpenseItemType expenseItemType = (ExpenseItemType)object;

		long primaryKey = expenseItemType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ExpenseItemType> toCacheModel() {
		ExpenseItemTypeCacheModel expenseItemTypeCacheModel =
			new ExpenseItemTypeCacheModel();

		expenseItemTypeCacheModel.expenseItemTypeId = getExpenseItemTypeId();

		expenseItemTypeCacheModel.groupId = getGroupId();

		expenseItemTypeCacheModel.companyId = getCompanyId();

		expenseItemTypeCacheModel.userId = getUserId();

		expenseItemTypeCacheModel.userName = getUserName();

		String userName = expenseItemTypeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			expenseItemTypeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			expenseItemTypeCacheModel.createDate = createDate.getTime();
		}
		else {
			expenseItemTypeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			expenseItemTypeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			expenseItemTypeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		expenseItemTypeCacheModel.title = getTitle();

		String title = expenseItemTypeCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			expenseItemTypeCacheModel.title = null;
		}

		expenseItemTypeCacheModel.value = getValue();

		String value = expenseItemTypeCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			expenseItemTypeCacheModel.value = null;
		}

		expenseItemTypeCacheModel.status = getStatus();

		return expenseItemTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ExpenseItemType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ExpenseItemType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExpenseItemType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ExpenseItemType)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ExpenseItemType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ExpenseItemType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExpenseItemType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ExpenseItemType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ExpenseItemType>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _expenseItemTypeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _title;
	private String _value;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		Function<ExpenseItemType, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ExpenseItemType)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("expenseItemTypeId", _expenseItemTypeId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("value", _value);
		_columnOriginalValues.put("status", _status);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("expenseItemTypeId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("title", 128L);

		columnBitmasks.put("value", 256L);

		columnBitmasks.put("status", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ExpenseItemType _escapedModel;

}