/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.me.expense.manager.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.me.expense.manager.model.Translation;
import com.liferay.me.expense.manager.model.TranslationModel;
import com.liferay.me.expense.manager.model.TranslationSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Translation service. Represents a row in the &quot;ExpenseManager_Translation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TranslationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TranslationImpl}.
 * </p>
 *
 * @author Mahmoud Hussein Tayem
 * @see TranslationImpl
 * @generated
 */
@JSON(strict = true)
public class TranslationModelImpl
	extends BaseModelImpl<Translation> implements TranslationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a translation model instance should use the <code>Translation</code> interface instead.
	 */
	public static final String TABLE_NAME = "ExpenseManager_Translation";

	public static final Object[][] TABLE_COLUMNS = {
		{"translationId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"portletId", Types.VARCHAR},
		{"componentId", Types.VARCHAR}, {"key_", Types.VARCHAR},
		{"cultureCode", Types.VARCHAR}, {"translationValue", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("translationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("portletId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("componentId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("key_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cultureCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("translationValue", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ExpenseManager_Translation (translationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,portletId VARCHAR(75) null,componentId VARCHAR(75) null,key_ VARCHAR(75) null,cultureCode VARCHAR(75) null,translationValue VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ExpenseManager_Translation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY translation.translationId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ExpenseManager_Translation.translationId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPONENTID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CULTURECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PORTLETID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TRANSLATIONID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Translation toModel(TranslationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Translation model = new TranslationImpl();

		model.setTranslationId(soapModel.getTranslationId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPortletId(soapModel.getPortletId());
		model.setComponentId(soapModel.getComponentId());
		model.setKey(soapModel.getKey());
		model.setCultureCode(soapModel.getCultureCode());
		model.setTranslationValue(soapModel.getTranslationValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Translation> toModels(TranslationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Translation> models = new ArrayList<Translation>(
			soapModels.length);

		for (TranslationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TranslationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _translationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTranslationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _translationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Translation.class;
	}

	@Override
	public String getModelClassName() {
		return Translation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Translation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Translation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Translation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Translation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Translation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Translation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Translation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Translation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Translation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Translation>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Translation.class.getClassLoader(), Translation.class,
			ModelWrapper.class);

		try {
			Constructor<Translation> constructor =
				(Constructor<Translation>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Translation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Translation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Translation, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Translation, Object>>();
		Map<String, BiConsumer<Translation, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Translation, ?>>();

		attributeGetterFunctions.put(
			"translationId", Translation::getTranslationId);
		attributeSetterBiConsumers.put(
			"translationId",
			(BiConsumer<Translation, Long>)Translation::setTranslationId);
		attributeGetterFunctions.put("groupId", Translation::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Translation, Long>)Translation::setGroupId);
		attributeGetterFunctions.put("companyId", Translation::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Translation, Long>)Translation::setCompanyId);
		attributeGetterFunctions.put("userId", Translation::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Translation, Long>)Translation::setUserId);
		attributeGetterFunctions.put("userName", Translation::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Translation, String>)Translation::setUserName);
		attributeGetterFunctions.put("createDate", Translation::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Translation, Date>)Translation::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Translation::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Translation, Date>)Translation::setModifiedDate);
		attributeGetterFunctions.put("portletId", Translation::getPortletId);
		attributeSetterBiConsumers.put(
			"portletId",
			(BiConsumer<Translation, String>)Translation::setPortletId);
		attributeGetterFunctions.put(
			"componentId", Translation::getComponentId);
		attributeSetterBiConsumers.put(
			"componentId",
			(BiConsumer<Translation, String>)Translation::setComponentId);
		attributeGetterFunctions.put("key", Translation::getKey);
		attributeSetterBiConsumers.put(
			"key", (BiConsumer<Translation, String>)Translation::setKey);
		attributeGetterFunctions.put(
			"cultureCode", Translation::getCultureCode);
		attributeSetterBiConsumers.put(
			"cultureCode",
			(BiConsumer<Translation, String>)Translation::setCultureCode);
		attributeGetterFunctions.put(
			"translationValue", Translation::getTranslationValue);
		attributeSetterBiConsumers.put(
			"translationValue",
			(BiConsumer<Translation, String>)Translation::setTranslationValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTranslationId() {
		return _translationId;
	}

	@Override
	public void setTranslationId(long translationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_translationId = translationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTranslationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("translationId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getPortletId() {
		if (_portletId == null) {
			return "";
		}
		else {
			return _portletId;
		}
	}

	@Override
	public void setPortletId(String portletId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_portletId = portletId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalPortletId() {
		return getColumnOriginalValue("portletId");
	}

	@JSON
	@Override
	public String getComponentId() {
		if (_componentId == null) {
			return "";
		}
		else {
			return _componentId;
		}
	}

	@Override
	public void setComponentId(String componentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_componentId = componentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalComponentId() {
		return getColumnOriginalValue("componentId");
	}

	@JSON
	@Override
	public String getKey() {
		if (_key == null) {
			return "";
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_key = key;
	}

	@JSON
	@Override
	public String getCultureCode() {
		if (_cultureCode == null) {
			return "";
		}
		else {
			return _cultureCode;
		}
	}

	@Override
	public void setCultureCode(String cultureCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cultureCode = cultureCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCultureCode() {
		return getColumnOriginalValue("cultureCode");
	}

	@JSON
	@Override
	public String getTranslationValue() {
		if (_translationValue == null) {
			return "";
		}
		else {
			return _translationValue;
		}
	}

	@Override
	public void setTranslationValue(String translationValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_translationValue = translationValue;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Translation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Translation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Translation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TranslationImpl translationImpl = new TranslationImpl();

		translationImpl.setTranslationId(getTranslationId());
		translationImpl.setGroupId(getGroupId());
		translationImpl.setCompanyId(getCompanyId());
		translationImpl.setUserId(getUserId());
		translationImpl.setUserName(getUserName());
		translationImpl.setCreateDate(getCreateDate());
		translationImpl.setModifiedDate(getModifiedDate());
		translationImpl.setPortletId(getPortletId());
		translationImpl.setComponentId(getComponentId());
		translationImpl.setKey(getKey());
		translationImpl.setCultureCode(getCultureCode());
		translationImpl.setTranslationValue(getTranslationValue());

		translationImpl.resetOriginalValues();

		return translationImpl;
	}

	@Override
	public int compareTo(Translation translation) {
		long primaryKey = translation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Translation)) {
			return false;
		}

		Translation translation = (Translation)object;

		long primaryKey = translation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Translation> toCacheModel() {
		TranslationCacheModel translationCacheModel =
			new TranslationCacheModel();

		translationCacheModel.translationId = getTranslationId();

		translationCacheModel.groupId = getGroupId();

		translationCacheModel.companyId = getCompanyId();

		translationCacheModel.userId = getUserId();

		translationCacheModel.userName = getUserName();

		String userName = translationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			translationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			translationCacheModel.createDate = createDate.getTime();
		}
		else {
			translationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			translationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			translationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		translationCacheModel.portletId = getPortletId();

		String portletId = translationCacheModel.portletId;

		if ((portletId != null) && (portletId.length() == 0)) {
			translationCacheModel.portletId = null;
		}

		translationCacheModel.componentId = getComponentId();

		String componentId = translationCacheModel.componentId;

		if ((componentId != null) && (componentId.length() == 0)) {
			translationCacheModel.componentId = null;
		}

		translationCacheModel.key = getKey();

		String key = translationCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			translationCacheModel.key = null;
		}

		translationCacheModel.cultureCode = getCultureCode();

		String cultureCode = translationCacheModel.cultureCode;

		if ((cultureCode != null) && (cultureCode.length() == 0)) {
			translationCacheModel.cultureCode = null;
		}

		translationCacheModel.translationValue = getTranslationValue();

		String translationValue = translationCacheModel.translationValue;

		if ((translationValue != null) && (translationValue.length() == 0)) {
			translationCacheModel.translationValue = null;
		}

		return translationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Translation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Translation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Translation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Translation)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Translation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Translation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Translation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Translation)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Translation>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _translationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _portletId;
	private String _componentId;
	private String _key;
	private String _cultureCode;
	private String _translationValue;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Translation, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Translation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("translationId", _translationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("portletId", _portletId);
		_columnOriginalValues.put("componentId", _componentId);
		_columnOriginalValues.put("key_", _key);
		_columnOriginalValues.put("cultureCode", _cultureCode);
		_columnOriginalValues.put("translationValue", _translationValue);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("key_", "key");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("translationId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("portletId", 128L);

		columnBitmasks.put("componentId", 256L);

		columnBitmasks.put("key_", 512L);

		columnBitmasks.put("cultureCode", 1024L);

		columnBitmasks.put("translationValue", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Translation _escapedModel;

}